import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import { getServerPageNovels } from "@/generated/page";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  if (!data) {
    return "No data";
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          {data?.novels?.map((novel) => (
            <div key={novel?.id}>
              <h1>{novel?.title}</h1>
              <h3>
                Author:{" "}
                {novel?.authors?.map((author) => author?.name).join(", ")}
              </h3>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  return await getServerPageNovels({}, ctx);
};
